dist: focal
language: node_js
node_js: 18
cache:
  bundler: true
  pip: true
  npm: true
# before_install:
# - pyenv local 3.6
install:
# - travis_retry gem install s3_website -v 3.4.0
# - travis_retry pip install awscli --upgrade --user
- travis_retry npm ci
script:
- npm run lint
- npm run test
- npm run build
# - npm run build:storybook
# after_success:
# - ./.travis-deploy.sh
